/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/models/3dwebsite_v_7.glb 
*/

import React from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/3dwebsite_v_7.glb");
  return (
    <group {...props} dispose={null} position={[100, 100, 100]} scale={15}>
      <PerspectiveCamera
        makeDefault={false}
        far={100}
        near={3.5}
        fov={22.895}
        position={[19.543, -0.171, -8.607]}
        rotation={[-1.547, 1.497, 1.547]}
      />
      <group scale={[4.572, 1.829, 5.334]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials["Wooden Floor"]}
        />
        <mesh
          geometry={nodes.Cube_3.geometry}
          material={materials["Third Room wall color"]}
        />
        <mesh
          geometry={nodes.Cube_4.geometry}
          material={materials["Second Room wall color"]}
        />
        <mesh geometry={nodes.Cube_5.geometry} material={materials.Glass} />
      </group>
      <mesh
        geometry={nodes.CTRL_Hole.geometry}
        material={materials.hidden_material}
        position={[8.13, -1.787, -10.917]}
        scale={[0.932, 1.816, 0.652]}
      />
      <group position={[8.13, -1.787, -10.917]} scale={[0.932, 1.816, 0.652]}>
        <mesh geometry={nodes.Window_1.geometry} material={materials.PVC} />
        <mesh geometry={nodes.Window_2.geometry} material={materials.Plastic} />
        <mesh geometry={nodes.Window_3.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Window_4.geometry} material={materials.Marble} />
      </group>
      <mesh
        geometry={nodes.Sofa.geometry}
        material={nodes.Sofa.material}
        position={[1.237, -1.567, -4.803]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.222, -1]}
      />
      <mesh
        geometry={nodes.Gate.geometry}
        material={materials.Material}
        scale={[4.572, 1.829, 5.334]}
      />
      <mesh
        geometry={nodes["3dwebsite-background"].geometry}
        material={materials["3dwebsite-background"]}
        position={[2.468, -0.64, -17.88]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={16.684}
      />
      <group scale={[4.572, 1.829, 5.334]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.Material} />
        <mesh
          geometry={nodes.Cube003_1.geometry}
          material={materials["Projects Box"]}
        />
      </group>
      <group scale={[4.572, 1.829, 5.334]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Material} />
        <mesh
          geometry={nodes.Cube004_1.geometry}
          material={materials["Projects Box"]}
        />
      </group>
      <group scale={[4.572, 1.829, 5.334]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.Material} />
        <mesh
          geometry={nodes.Cube005_1.geometry}
          material={materials["Projects Box"]}
        />
      </group>
      <mesh
        geometry={nodes.Project_01.geometry}
        material={materials["Material.001"]}
        position={[12.615, -0.372, -7.464]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.021, -0.448, -0.296]}
      />
      <mesh
        geometry={nodes.Project_01_Sub_Heading.geometry}
        material={nodes.Project_01_Sub_Heading.material}
        position={[12.597, -0.89, -7.157]}
        rotation={[1.569, 0.012, -1.562]}
        scale={[0.027, 1.043, 0.026]}
      />
      <mesh
        geometry={nodes.GN_Instance.geometry}
        material={nodes.GN_Instance.material}
        position={[12.597, -0.89, -7.157]}
        rotation={[1.569, 0.012, -1.562]}
        scale={[0.027, 1.043, 0.026]}
      />
      <mesh
        geometry={nodes.Project_01_Heading.geometry}
        material={nodes.Project_01_Heading.material}
        position={[12.597, -0.94, -7.157]}
        rotation={[1.569, 0.012, -1.562]}
        scale={[0.038, 1.043, 0.043]}
      />
      <mesh
        geometry={nodes.GN_Instance_1.geometry}
        material={nodes.GN_Instance_1.material}
        position={[12.597, -0.94, -7.157]}
        rotation={[1.569, 0.012, -1.562]}
        scale={[0.038, 1.043, 0.043]}
      />
      <mesh
        geometry={nodes.Project_02.geometry}
        material={materials["Material.001"]}
        position={[12.615, -0.372, -8.662]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.021, -0.448, -0.296]}
      />
      <mesh
        geometry={nodes.Project_02_Sub_Heading.geometry}
        material={nodes.Project_02_Sub_Heading.material}
        position={[12.597, -0.89, -8.355]}
        rotation={[1.569, 0.012, -1.562]}
        scale={[0.027, 1.043, 0.026]}
      />
      <mesh
        geometry={nodes.GN_Instance_2.geometry}
        material={nodes.GN_Instance_2.material}
        position={[12.597, -0.89, -8.355]}
        rotation={[1.569, 0.012, -1.562]}
        scale={[0.027, 1.043, 0.026]}
      />
      <mesh
        geometry={nodes.Project_02_Heading.geometry}
        material={nodes.Project_02_Heading.material}
        position={[12.597, -0.94, -8.355]}
        rotation={[1.569, 0.012, -1.562]}
        scale={[0.038, 1.043, 0.043]}
      />
      <mesh
        geometry={nodes.GN_Instance_3.geometry}
        material={nodes.GN_Instance_3.material}
        position={[12.597, -0.94, -8.355]}
        rotation={[1.569, 0.012, -1.562]}
        scale={[0.038, 1.043, 0.043]}
      />
      <mesh
        geometry={nodes.Project_03.geometry}
        material={materials["Material.001"]}
        position={[12.615, -0.372, -9.915]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.021, -0.448, -0.296]}
      />
      <mesh
        geometry={nodes.Project_03_Sub_Heading.geometry}
        material={nodes.Project_03_Sub_Heading.material}
        position={[12.597, -0.89, -9.609]}
        rotation={[1.569, 0.012, -1.562]}
        scale={[0.027, 1.043, 0.026]}
      />
      <mesh
        geometry={nodes.GN_Instance_4.geometry}
        material={nodes.GN_Instance_4.material}
        position={[12.597, -0.89, -9.609]}
        rotation={[1.569, 0.012, -1.562]}
        scale={[0.027, 1.043, 0.026]}
      />
      <mesh
        geometry={nodes.Project_03_Heading.geometry}
        material={nodes.Project_03_Heading.material}
        position={[12.597, -0.94, -9.609]}
        rotation={[1.569, 0.012, -1.562]}
        scale={[0.038, 1.043, 0.043]}
      />
      <mesh
        geometry={nodes.GN_Instance_5.geometry}
        material={nodes.GN_Instance_5.material}
        position={[12.597, -0.94, -9.609]}
        rotation={[1.569, 0.012, -1.562]}
        scale={[0.038, 1.043, 0.043]}
      />
    </group>
  );
}

useGLTF.preload("/models/3dwebsite_v_7.glb");
