/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../public/models/new-scene-9.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, scene } = useGLTF("/models/new-scene-9.glb");

  useEffect(() => {
    group.current.traverse((child) => {
      if (child.isMesh) {
        child.castShadow = true;
        child.receiveShadow = true;
      }
    });
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Box001.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["07 - Default"]}
      />
      <mesh
        geometry={nodes.Box046.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box047.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box048.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box049.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box050.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box051.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box052.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box053.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box054.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box055.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box056.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box057.geometry}
        material={materials["08 - Default"]}
      />
      <mesh
        geometry={nodes.Box058.geometry}
        material={materials["08 - Default"]}
      />
      <mesh
        geometry={nodes.Box059.geometry}
        material={materials["08 - Default"]}
      />
      <mesh
        geometry={nodes.Box060.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box061.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box062.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box063.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box064.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box065.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box066.geometry}
        material={materials["08 - Default"]}
      />
      <mesh
        geometry={nodes.Box067.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box068.geometry}
        material={materials["08 - Default"]}
      />
      <mesh
        geometry={nodes.Box069.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box070.geometry}
        material={materials["08 - Default"]}
      />
      <mesh
        geometry={nodes.Box071.geometry}
        material={materials["08 - Default"]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["07 - Default"]}
      />
      <mesh
        geometry={nodes.Box072.geometry}
        material={materials["07 - Default"]}
      />
      <mesh
        geometry={nodes.Box073.geometry}
        material={materials["07 - Default"]}
      />
      <mesh
        geometry={nodes.Box074.geometry}
        material={materials["08 - Default"]}
      />
      <mesh
        geometry={nodes.Box075.geometry}
        material={materials["08 - Default"]}
      />
      <mesh
        geometry={nodes.Box076.geometry}
        material={materials["08 - Default"]}
      />
      <mesh
        geometry={nodes.Box077.geometry}
        material={materials["08 - Default"]}
      />
      <mesh
        geometry={nodes.Box078.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box079.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box080.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box081.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box082.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box083.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box084.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box085.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box086.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box087.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box088.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box089.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box090.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Plane008001.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box085001.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Box085002.geometry}
        material={materials["02 - Decton 1"]}
      />
      <mesh
        geometry={nodes.Text_intro.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.Text_intro001.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.Text_intro002.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.Text_intro003.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.Text_intro004.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.Text_intro005.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.Text_intro006.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Text_intro007.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Text_intro008.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Text_intro009.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Text_intro010.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.Text_intro011.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Text_intro012.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.Text_intro013.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Text_intro014.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Text_intro015.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Text_intro016.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Text_intro017.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Text_intro018.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Text_intro019.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Text_intro020.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        geometry={nodes.Text_intro021.geometry}
        material={materials.Material}
      />
      <mesh geometry={nodes.Plane004_1.geometry} material={materials.Logo} />
      <mesh geometry={nodes.Plane002_1.geometry} material={materials.Logo} />
      <mesh
        geometry={nodes.Text_intro022.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.Plane003_1.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        geometry={nodes.Plane005_1.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        geometry={nodes.Text_intro023.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.Box080001.geometry}
        material={materials["Screen curved 1"]}
      />
      <mesh
        geometry={nodes.Text_intro024.geometry}
        material={materials.Material}
      />
      <mesh geometry={nodes.Trunk.geometry} material={materials.Tree_Mlt}>
        <mesh
          geometry={nodes.Flower.geometry}
          material={materials.Flower_Mlt}
        />
      </mesh>
      <mesh geometry={nodes.Plane006_1.geometry} material={materials.Logo} />
      <mesh
        geometry={nodes.Mesh048.geometry}
        material={materials["09 - owl"]}
      />
      <mesh geometry={nodes.Mesh048_1.geometry} material={materials.Frame} />
      <mesh
        geometry={nodes.Mesh049.geometry}
        material={materials["09 - sky cosmetecs"]}
      />
      <mesh geometry={nodes.Mesh049_1.geometry} material={materials.Frame} />
      <mesh
        geometry={nodes.Mesh050.geometry}
        material={materials["09 - travy scot"]}
      />
      <mesh geometry={nodes.Mesh050_1.geometry} material={materials.Frame} />
      <mesh
        geometry={nodes.Mesh051.geometry}
        material={materials["09 - elcome V3 sound 2"]}
      />
      <mesh geometry={nodes.Mesh051_1.geometry} material={materials.Frame} />
      <mesh
        geometry={nodes.Mesh052.geometry}
        material={materials["09 - Gal Gadot"]}
      />
      <mesh geometry={nodes.Mesh052_1.geometry} material={materials.Frame} />
      <mesh
        geometry={nodes.Mesh053.geometry}
        material={materials["09 - Decton Bobi"]}
      />
      <mesh geometry={nodes.Mesh053_1.geometry} material={materials.Frame} />
      <mesh
        geometry={nodes.Mesh055.geometry}
        material={materials["09 - Nova.001"]}
      />
      <mesh geometry={nodes.Mesh055_1.geometry} material={materials.Frame} />
      <mesh
        geometry={nodes.Mesh056.geometry}
        material={materials["09 - Skylrk 3"]}
      />
      <mesh geometry={nodes.Mesh056_1.geometry} material={materials.Frame} />
      <mesh
        geometry={nodes.Mesh057.geometry}
        material={materials["09 - SpaceX"]}
      />
      <mesh geometry={nodes.Mesh057_1.geometry} material={materials.Frame} />
      <mesh
        geometry={nodes.Mesh058.geometry}
        material={materials["09 - Flowers "]}
      />
      <mesh geometry={nodes.Mesh058_1.geometry} material={materials.Frame} />
      <mesh
        geometry={nodes.Mesh073.geometry}
        material={materials["09 - Tomi House NYC"]}
      />
      <mesh geometry={nodes.Mesh073_1.geometry} material={materials.Frame} />
      <mesh
        geometry={nodes.Mesh054.geometry}
        material={materials["09 - Fishes"]}
      />
      <mesh geometry={nodes.Mesh054_1.geometry} material={materials.Frame} />
      <mesh
        geometry={nodes.Mesh074.geometry}
        material={materials["Screen curved 1"]}
      />
      <mesh geometry={nodes.Mesh074_1.geometry} material={materials.Frame} />
    </group>
  );
}

useGLTF.preload("/models/new-scene-9.glb");
